### ISSUE TITLE
CUDA Out of Memory when running 'imagenetv2' and 'imagenet_sketch' datasets

### ISSUE THREAD

**Issue by XiudingCai** [jameelhassan/PromptAlign#13]
Hi,

I'm encountering a CUDA Out of Memory error while trying to run the imagenetv2 and imagenet_sketch datasets with the provided script. The script works fine for imagenet_a, but for the other datasets, I receive an error message: torch.cuda.OutOfMemoryError: CUDA out of memory. I have attempted to set the batch size to as low as 1, but it does not resolve the issue.

Thanks!

**Comment by fengpany** [comment]
> Hi,
> 
> I'm encountering a CUDA Out of Memory error while trying to run the imagenetv2 and imagenet_sketch datasets with the provided script. The script works fine for imagenet_a, but for the other datasets, I receive an error message: torch.cuda.OutOfMemoryError: CUDA out of memory. I have attempted to set the batch size to as low as 1, but it does not resolve the issue.
> 
> Thanks!

Did you solve the issue? I encountered the same problem.

**Comment by jameelhassan** [comment]
Hi,
The number of classes for ImagenetV2 and Imagenet-Sketch are 1000, which increases the memory occupied by the text-encoder. Setting a lower batch size will not help with this, since the TTA batch size used is 1. One option could be to check if the model can be loaded in a lower precision (needs to be implemented by yourself).
